import axios from 'axios';

const apiUrl = `${process.env.REACT_APP_API_URL}/Dorm_ReportTraffic?fromDate=1399-07-01&toDate=1399-10-10&idnumber=952011307002&DormId=0&reportTyp=4&pageNumber=1&pageSize=10&orderby=id&ordertype=desc`;

export const insert = (data) => {
    axios.post(apiUrl, data)
    .then((result) => {return result.data;})
    .catch((error) => {return error});
}

export const insertAsync = async(data) => {
    const response = await axios.post(apiUrl, data);
    return response.data ;
}

export const getAll = () => {
    axios.get(apiUrl)
    .then(result => {return result.data;})
    .catch((error) => {return error;})
}

export const getAllAsync = async() => {
    const response = await axios.get(apiUrl);
    // response.data = sampleData;
    return response.data;
}

const sampleData= [
    {
    "IdNumber": "952011307002",
    "FirstName": "بتول",
    "LastName": "زمانی فرادنبه",
    "FLname": "بتول زمانی فرادنبه",
    "DormNumber": "نيك نژادي",
    "BlockNumber": "مهندسی مكانیك - تبدیل انرژی",
    "RoomNumber": "560",
    "event": 16,
    "eventDate": "1399-07-22",
    "eventTime": "14:16:18",
    "EventTitle": "ورود",
    "Title": "ورود 2 - نیک نژادی",
    "DeviceId": 2,
    "GroupDeviceId": 0,
    "OperatorId": null,
    "Operator": null,
    "Mobile": null,
    "Phone": null,
    "Description": "با کارت",
    "DiffDate": 0,
    "Selected": true,
    "Radif": 1
    },
    {
    "IdNumber": "952011307002",
    "FirstName": "بتول",
    "LastName": "زمانی فرادنبه",
    "FLname": "بتول زمانی فرادنبه",
    "DormNumber": "نيك نژادي",
    "BlockNumber": "مهندسی مكانیك - تبدیل انرژی",
    "RoomNumber": "560",
    "event": 32,
    "eventDate": "1399-07-23",
    "eventTime": "16:56:39",
    "EventTitle": "خروج",
    "Title": "خروج 1 - نیک نژادی",
    "DeviceId": 3,
    "GroupDeviceId": 0,
    "OperatorId": null,
    "Operator": null,
    "Mobile": null,
    "Phone": null,
    "Description": "با کارت",
    "DiffDate": 0,
    "Selected": true,
    "Radif": 2
    },
    {
    "IdNumber": "952011307002",
    "FirstName": "بتول",
    "LastName": "زمانی فرادنبه",
    "FLname": "بتول زمانی فرادنبه",
    "DormNumber": "نيك نژادي",
    "BlockNumber": "مهندسی مكانیك - تبدیل انرژی",
    "RoomNumber": "560",
    "event": 16,
    "eventDate": "1399-07-23",
    "eventTime": "16:56:43",
    "EventTitle": "ورود",
    "Title": "ورود 1 - نیک نژادی",
    "DeviceId": 1,
    "GroupDeviceId": 0,
    "OperatorId": null,
    "Operator": null,
    "Mobile": null,
    "Phone": null,
    "Description": "با کارت",
    "DiffDate": 0,
    "Selected": true,
    "Radif": 3
    },
    {
    "IdNumber": "952011307002",
    "FirstName": "بتول",
    "LastName": "زمانی فرادنبه",
    "FLname": "بتول زمانی فرادنبه",
    "DormNumber": "نيك نژادي",
    "BlockNumber": "مهندسی مكانیك - تبدیل انرژی",
    "RoomNumber": "560",
    "event": 32,
    "eventDate": "1399-07-27",
    "eventTime": "09:19:40",
    "EventTitle": "خروج",
    "Title": "خروج 1 - نیک نژادی",
    "DeviceId": 3,
    "GroupDeviceId": 0,
    "OperatorId": null,
    "Operator": null,
    "Mobile": null,
    "Phone": null,
    "Description": "با کارت",
    "DiffDate": 0,
    "Selected": true,
    "Radif": 4
    },
    {
    "IdNumber": "952011307002",
    "FirstName": "بتول",
    "LastName": "زمانی فرادنبه",
    "FLname": "بتول زمانی فرادنبه",
    "DormNumber": "نيك نژادي",
    "BlockNumber": "مهندسی مكانیك - تبدیل انرژی",
    "RoomNumber": "560",
    "event": 16,
    "eventDate": "1399-07-27",
    "eventTime": "15:56:49",
    "EventTitle": "ورود",
    "Title": "ورود 1 - نیک نژادی",
    "DeviceId": 1,
    "GroupDeviceId": 0,
    "OperatorId": null,
    "Operator": null,
    "Mobile": null,
    "Phone": null,
    "Description": "با کارت",
    "DiffDate": 0,
    "Selected": true,
    "Radif": 5
    },
    {
    "IdNumber": "952011307002",
    "FirstName": "بتول",
    "LastName": "زمانی فرادنبه",
    "FLname": "بتول زمانی فرادنبه",
    "DormNumber": "نيك نژادي",
    "BlockNumber": "مهندسی مكانیك - تبدیل انرژی",
    "RoomNumber": "560",
    "event": 32,
    "eventDate": "1399-07-27",
    "eventTime": "17:50:18",
    "EventTitle": "خروج",
    "Title": "خروج 3 - فهميده",
    "DeviceId": 10,
    "GroupDeviceId": 0,
    "OperatorId": null,
    "Operator": null,
    "Mobile": null,
    "Phone": null,
    "Description": "با کارت",
    "DiffDate": 0,
    "Selected": true,
    "Radif": 6
    },
    {
    "IdNumber": "952011307002",
    "FirstName": "بتول",
    "LastName": "زمانی فرادنبه",
    "FLname": "بتول زمانی فرادنبه",
    "DormNumber": "نيك نژادي",
    "BlockNumber": "مهندسی مكانیك - تبدیل انرژی",
    "RoomNumber": "560",
    "event": 16,
    "eventDate": "1399-07-27",
    "eventTime": "18:25:59",
    "EventTitle": "ورود",
    "Title": "ورود 3 - فهميده",
    "DeviceId": 8,
    "GroupDeviceId": 0,
    "OperatorId": null,
    "Operator": null,
    "Mobile": null,
    "Phone": null,
    "Description": "با کارت",
    "DiffDate": 0,
    "Selected": true,
    "Radif": 7
    },
    {
    "IdNumber": "952011307002",
    "FirstName": "بتول",
    "LastName": "زمانی فرادنبه",
    "FLname": "بتول زمانی فرادنبه",
    "DormNumber": "نيك نژادي",
    "BlockNumber": "مهندسی مكانیك - تبدیل انرژی",
    "RoomNumber": "560",
    "event": 32,
    "eventDate": "1399-07-28",
    "eventTime": "13:28:49",
    "EventTitle": "خروج",
    "Title": "خروج 1 - نیک نژادی",
    "DeviceId": 3,
    "GroupDeviceId": 0,
    "OperatorId": null,
    "Operator": null,
    "Mobile": null,
    "Phone": null,
    "Description": "با کارت",
    "DiffDate": 0,
    "Selected": true,
    "Radif": 8
    },
    {
    "IdNumber": "952011307002",
    "FirstName": "بتول",
    "LastName": "زمانی فرادنبه",
    "FLname": "بتول زمانی فرادنبه",
    "DormNumber": "نيك نژادي",
    "BlockNumber": "مهندسی مكانیك - تبدیل انرژی",
    "RoomNumber": "560",
    "event": 16,
    "eventDate": "1399-07-28",
    "eventTime": "15:15:43",
    "EventTitle": "ورود",
    "Title": "ورود 2 - نیک نژادی",
    "DeviceId": 2,
    "GroupDeviceId": 0,
    "OperatorId": null,
    "Operator": null,
    "Mobile": null,
    "Phone": null,
    "Description": "با کارت",
    "DiffDate": 0,
    "Selected": true,
    "Radif": 9
    },
    {
    "IdNumber": "952011307002",
    "FirstName": "بتول",
    "LastName": "زمانی فرادنبه",
    "FLname": "بتول زمانی فرادنبه",
    "DormNumber": "نيك نژادي",
    "BlockNumber": "مهندسی مكانیك - تبدیل انرژی",
    "RoomNumber": "560",
    "event": 32,
    "eventDate": "1399-07-28",
    "eventTime": "18:39:07",
    "EventTitle": "خروج",
    "Title": "خروج 3 - فهميده",
    "DeviceId": 10,
    "GroupDeviceId": 0,
    "OperatorId": null,
    "Operator": null,
    "Mobile": null,
    "Phone": null,
    "Description": "با کارت",
    "DiffDate": 0,
    "Selected": true,
    "Radif": 10
    }
    ]